# Generated by Django 3.0.dev20190528134031 on 2019-06-13 06:21

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('url_text', models.CharField(max_length=200)),
                ('rss_text', models.CharField(max_length=200)),
                ('author_text', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=40, verbose_name=django.contrib.auth.models.User)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
