# Generated by Django 3.0.dev20190528134031 on 2019-06-13 06:41

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='created_by',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=20),
        ),
    ]
