# Generated by Django 3.0.dev20190528134031 on 2019-06-18 05:44

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_auto_20190613_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='author_text',
            field=models.CharField(max_length=50, null=True, verbose_name='Enter Author Name'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='created_by',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=20, null=True, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='rss_text',
            field=models.CharField(max_length=200, verbose_name='Enter RSS'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='title_text',
            field=models.CharField(max_length=200, verbose_name='Enter Title'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='url_text',
            field=models.CharField(max_length=200, verbose_name='Enter URL'),
        ),
    ]
